# Generated by Django 3.1.5 on 2021-01-06 05:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2021, 2, 5, 5, 14, 59, 227321, tzinfo=utc))),
            ],
        ),
    ]
