# Generated by Django 3.1.5 on 2021-01-06 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20210106_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 5, 38, 58, 349064, tzinfo=utc)),
        ),
    ]
