# Generated by Django 3.1.5 on 2021-01-06 05:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20210106_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=70)),
                ('task_detail', models.CharField(max_length=200, null=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2021, 1, 7, 5, 44, 7, 616098, tzinfo=utc))),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=70)),
                ('task_detail', models.CharField(max_length=200, null=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2021, 1, 13, 5, 44, 7, 615075, tzinfo=utc))),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 5, 44, 7, 613974, tzinfo=utc)),
        ),
    ]
